name: CreateRelease

on:
  push:
    tags:
      - '*'

jobs:
  public-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew distZip
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            */build/distributions/distribution.zip
            build/distributions/distribution.zip